--                                                                                                  role
INSERT INTO S_UPRAWNIENIA(ID, NAZWA)
VALUES (1, 'ADMIN');
INSERT INTO S_UPRAWNIENIA(ID, NAZWA)
VALUES (2, 'USER');
INSERT INTO S_UPRAWNIENIA(ID, NAZWA)
VALUES (3, 'EMPLOYEE');

--                                                                                                  słownik osób
INSERT INTO S_TYP_OSOBY(ID, NAZWA)
VALUES (1, 'CLIENT');
INSERT INTO S_TYP_OSOBY(ID, NAZWA)
VALUES (2, 'EMPLOYEE');
INSERT INTO S_TYP_OSOBY(ID, NAZWA)
VALUES (3, 'INSTRUCTOR');

--                                                                                                  użytkownicy
INSERT INTO USERS(ID, LOGIN, HASLO, ID_S_UPRAWNIENIA)
VALUES (1, 'admin', '$2a$10$lXojkbR.q2zWWqlTgjQMUu1EZu7TD.vBZ03VC.ycrcxft2sr7qVmG', 1);

--                                                                                                  slowniki
INSERT INTO S_GRUPY_WIEKOWE(ID, NAZWA)
VALUES (1, 'DZIECI');
INSERT INTO S_GRUPY_WIEKOWE(ID, NAZWA)
VALUES (2, 'MŁODZIEŻ');
INSERT INTO S_GRUPY_WIEKOWE(ID, NAZWA)
VALUES (3, 'DOROŚLI');
INSERT INTO S_GRUPY_WIEKOWE(ID, NAZWA)
VALUES (4, 'SENIORZY');


INSERT INTO S_POZIOM_ZAAWANSOWANIA(ID, NAZWA)
VALUES (1, 'POCZĄTKUJĄCY');
INSERT INTO S_POZIOM_ZAAWANSOWANIA(ID, NAZWA)
VALUES (2, 'ŚREDNIO-ZAAWANSOWANY');
INSERT INTO S_POZIOM_ZAAWANSOWANIA(ID, NAZWA)
VALUES (3, 'ZAAWANSOWANY');
INSERT INTO S_POZIOM_ZAAWANSOWANIA(ID, NAZWA)
VALUES (4, 'MASTER');

INSERT INTO S_STYL_TANECZNY(ID, NAZWA)
VALUES (1, 'TANIEC TOWARZYSKI');
INSERT INTO S_STYL_TANECZNY(ID, NAZWA)
VALUES (2, 'TANIEC NOWOCZESNY');
INSERT INTO S_STYL_TANECZNY(ID, NAZWA)
VALUES (3, 'SALSA');
INSERT INTO S_STYL_TANECZNY(ID, NAZWA)
VALUES (4, 'BACHATA');
INSERT INTO S_STYL_TANECZNY(ID, NAZWA)
VALUES (5, 'SAMBA');
INSERT INTO S_STYL_TANECZNY(ID, NAZWA)
VALUES (6, 'MODERN JAZZ');
INSERT INTO S_STYL_TANECZNY(ID, NAZWA)
VALUES (7, 'LADIES LATINO');
INSERT INTO S_STYL_TANECZNY(ID, NAZWA)
VALUES (8, 'TANIEC BRZUCHA');

INSERT INTO S_DNI_TYGODNIA(ID, NAZWA)
VALUES (1, 'PONIEDZIAŁEK');
INSERT INTO S_DNI_TYGODNIA(ID, NAZWA)
VALUES (2, 'WTOREK');
INSERT INTO S_DNI_TYGODNIA(ID, NAZWA)
VALUES (3, 'ŚRODA');
INSERT INTO S_DNI_TYGODNIA(ID, NAZWA)
VALUES (4, 'CZWARTEK');
INSERT INTO S_DNI_TYGODNIA(ID, NAZWA)
VALUES (5, 'PIĄTEK');
INSERT INTO S_DNI_TYGODNIA(ID, NAZWA)
VALUES (6, 'SOBOTA');
INSERT INTO S_DNI_TYGODNIA(ID, NAZWA)
VALUES (7, 'NIEDZIELA');

INSERT INTO S_KONTAKT_TYP(ID, NAZWA)
VALUES (1, 'TEL');
INSERT INTO S_KONTAKT_TYP(ID, NAZWA)
VALUES (2, 'EMAIL');